services:
  db:
    image: postgres:16
    container_name: snowboard-starter-db
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      # persistent data
      - snowboard-starter-db:/var/lib/postgresql/data

volumes:
  snowboard-starter-db: